### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by Schwertspize** [D4edalus/CoD4x1.8_Server_Pub#6]
@PureTryOut asked [in the cuberite forum](https://forum.cuberite.org/thread-2425.html) for help for a nice and neat looking homepage. I decided to do so and after approximately one hour of coding and a bit more of peer-review (mostly by him but also @bearbin, thanks for that) i want to make this public. 

Reviews, advices or any notes welcome! (personally I feel like a bit too much color in the download section)

Note: you do NOT have to give a copyright notice on any sheet or something, although a mention in the list of overall contributors would be nice. 

Finally, the link: https://schwertspize.github.io
And the repo with the source: https://github.com/Schwertspize/schwertspize.github.io

Ps: not only style advice would be useful, also a bit more text for the various sections would be nice. If someone is experienced with grunt or other preprocessors, it would be awesome if they optimize the page after style review is done (I get 70-90% on Google PageInsight with a standard Apache, but funnily it thinks there is content on the right outside the real screen, this doesn't appear to be on a real device)

**Comment by D4edalus** [comment]
looks really good! the red and green looks a little weird :) just write yourself a little copyright notice on the bottom if you want to. we dont have a list of everyone who has contributed yet ... i think, but we wont forget you if we make one!
I like the text, it summarizes the most important benefits very well.

i have created a repositoy here, and added you as collaborator. if that's fine for you commit your stuff there ... and keep improving, its awesome :) https://github.com/D4edalus/cod4x_landingpage

**Comment by Schwertspize** [comment]
I'm closing development for today, it's somehow broken with the fonts. Maybe look into fonts.css (bootstrap.min.css is referring to that file (or should)) and look for the problem loafing the fonts. Moreover we got a little style problem on mobile devices, the content is larger than the screen, but nothing visible. Anyway,  end of the day

**Comment by Schwertspize** [comment]
So, fixed the few mobile bugs. 

I think we (probably you) shall create an organization, name it cod4x, then I will transfer my new repo to this organization and you rename it to cod4x.github.io and you got the website hosted for free (github pages). I will no longer push to the old repo, I updated the link in the first post, that's the new repo I will use

**Comment by IceNinjaman** [comment]
Hallo Schwertspize,
thank you so much for your work. I hope I can put that onto our site soon.

**Comment by Schwertspize** [comment]
If you make an organization, I can convert the repo at any time, and it is online under  organization-name.github.io (or if you set a cname record...)

**Comment by PureTryOut** [comment]
This can be closed btw.
