### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by wattz1979** [D4edalus/CoD4x1.8_Server_Pub#8]
Hi so sorry to post this here but i cant find any social media pages for your mod and cant see no other way of getting a forum mod's attention , i have tried registering at the forum and the answer to your question is not working ,added a screenshot so you can see it is entered correctly ,hope you can fix the issue soon cheers !

![screenshot_7](https://cloud.githubusercontent.com/assets/11533270/16059932/2aab9d86-327d-11e6-971c-e01d2104d568.png)

**Comment by IceNinjaman** [comment]
How about Call of Duty 4?
Or Call of Duty 4 - Modern Warfare

**Comment by wattz1979** [comment]
Thanks IceNinjaman greatly appreciated it was plain old Call of Duty 4 , i had tried Call of Duty 4 Modern Warfare and Modern Warfare with no luck
